[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# ✅ API routes - redirect to Netlify functions (MUST come FIRST)
[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/login"
  to = "/.netlify/functions/login"
  status = 200

[[redirects]]
  from = "/api/logout"
  to = "/.netlify/functions/logout"
  status = 200

[[redirects]]
  from = "/api/user/*"
  to = "/.netlify/functions/user"
  status = 200

[[redirects]]
  from = "/api/register"
  to = "/.netlify/functions/register"
  status = 200

[[redirects]]
  from = "/api/signup"
  to = "/.netlify/functions/signup"
  status = 200

[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

# ✅ SPA routes (React Router)
[[redirects]]
  from = "/signup"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/index.html"
  status = 200

# ✅ Catch-all for all other React Router paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ MIME type headers for JavaScript modules
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.mjs"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "dist"
  functions = "netlify/functions"
